# Generated by Django 4.0.4 on 2022-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, unique=True)),
                ('subtitulo', models.CharField(max_length=80)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posteos')),
            ],
        ),
    ]
