# Generated by Django 4.0.4 on 2022-05-31 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appPosteos', '0002_posteo_user_alter_posteo_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
