# Generated by Django 4.0.4 on 2022-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(null=b'I01\n'),
        ),
    ]
